/**
 * @Version: 1.0
 * @Author: Frederik
 * @Copyright: 2021 Upeo Consulting
 * @Uses:
 *
 * -----------------------------------------------------------------------------------------------
 * Description: Callout class, used to store callout information
 * -----------------------------------------------------------------------------------------------
 * Revision No. 	Author 			Date 			Description
 * 1.0 			Frederik 		12/08/2023 		Initial version
 * -----------------------------------------------------------------------------------------------
 *
 * Created: 12/08/2023
 * Last Updated: 12/08/2023
 *
 * Unit tests:
 *
 * -----------------------------------------------------------------------------------------------
*/


public class Callout {

    public String name;
    public String type;
    public String endpoint;
    public String body;
    public String method;
    public Map<String, String> headers;
    public String timeout;
    public String retry;


}